import uuid
from datetime import datetime
from typing import Optional, List
from sqlalchemy import String, Text, ForeignKey, Integer, DateTime, Boolean, Uuid
from sqlalchemy.orm import Mapped, mapped_column, relationship
from backend.app.models.base import Base

class Execution(Base):
    """
    Execution represents a complete autonomous software development pipeline run.
    """
    __tablename__ = "executions"

    project_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("projects.id", ondelete="CASCADE"), nullable=False)
    workflow_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("workflows.id", ondelete="CASCADE"), nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="Running", nullable=False) # Running, Paused, Cancelled, Completed
    current_stage: Mapped[str] = mapped_column(String(100), default="Requirement Analysis", nullable=False)
    started_at: Mapped[datetime] = mapped_column(DateTime, default=datetime.utcnow, nullable=False)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Relationships
    project: Mapped["Project"] = relationship(foreign_keys=[project_id])
    workflow: Mapped["Workflow"] = relationship(foreign_keys=[workflow_id])
    stages: Mapped[List["ExecutionStage"]] = relationship(back_populates="execution", cascade="all, delete-orphan")
    artifacts: Mapped[List["Artifact"]] = relationship(back_populates="execution", cascade="all, delete-orphan")
    deliverables: Mapped[List["Deliverable"]] = relationship(back_populates="execution", cascade="all, delete-orphan")

    def __repr__(self) -> str:
        return f"<Execution id={self.id} status={self.status} current_stage={self.current_stage}>"


class ExecutionStage(Base):
    """
    Represents an individual stage inside the execution pipeline.
    """
    __tablename__ = "execution_stages"

    execution_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("executions.id", ondelete="CASCADE"), nullable=False)
    name: Mapped[str] = mapped_column(String(100), nullable=False)
    status: Mapped[str] = mapped_column(String(50), default="Pending", nullable=False) # Pending, Running, Completed, Failed
    assigned_agent: Mapped[Optional[str]] = mapped_column(String(100), nullable=True) # Role or Name of agent
    started_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)
    completed_at: Mapped[Optional[datetime]] = mapped_column(DateTime, nullable=True)

    # Relationships
    execution: Mapped["Execution"] = relationship(back_populates="stages")

    def __repr__(self) -> str:
        return f"<ExecutionStage name={self.name} status={self.status}>"


class Artifact(Base):
    """
    Represents a design spec, doc, or file output generated by the pipeline.
    """
    __tablename__ = "execution_artifacts"

    execution_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("executions.id", ondelete="CASCADE"), nullable=False)
    type: Mapped[str] = mapped_column(String(100), nullable=False) # Architecture, API, Database, UI, SourceCode, etc.
    title: Mapped[str] = mapped_column(String(255), nullable=False)
    path: Mapped[str] = mapped_column(String(255), nullable=False)
    version: Mapped[str] = mapped_column(String(50), default="1.0.0", nullable=False)
    created_by: Mapped[Optional[uuid.UUID]] = mapped_column(Uuid, nullable=True)

    # Relationships
    execution: Mapped["Execution"] = relationship(back_populates="artifacts")

    def __repr__(self) -> str:
        return f"<Artifact type={self.type} title={self.title} version={self.version}>"


class Deliverable(Base):
    """
    Tracks formal checklists deliverables checking execution quality gates.
    """
    __tablename__ = "execution_deliverables"

    execution_id: Mapped[uuid.UUID] = mapped_column(Uuid, ForeignKey("executions.id", ondelete="CASCADE"), nullable=False)
    category: Mapped[str] = mapped_column(String(100), nullable=False) # Architecture, Database, Frontend, Backend, etc.
    status: Mapped[str] = mapped_column(String(50), default="Pending", nullable=False) # Pending, Completed
    artifact_id: Mapped[Optional[uuid.UUID]] = mapped_column(Uuid, ForeignKey("execution_artifacts.id", ondelete="SET NULL"), nullable=True)
    approved: Mapped[bool] = mapped_column(Boolean, default=False, nullable=False)

    # Relationships
    execution: Mapped["Execution"] = relationship(back_populates="deliverables")
    artifact: Mapped[Optional["Artifact"]] = relationship(foreign_keys=[artifact_id])

    def __repr__(self) -> str:
        return f"<Deliverable category={self.category} status={self.status} approved={self.approved}>"
