import os
import json
import base64
import logging
from typing import List, Dict, Any, Optional
from pydantic import BaseModel, Field

logger = logging.getLogger(__name__)

class GitHubRepoMetadata(BaseModel):
    name: str
    full_name: str
    owner: str
    html_url: str
    clone_url: str
    default_branch: str = "main"
    is_private: bool = True
    stars_count: int = 0
    forks_count: int = 0
    open_issues_count: int = 0

class GitHubBranch(BaseModel):
    name: str
    commit_sha: str
    protected: bool = False

class GitHubPullRequest(BaseModel):
    number: int
    title: str
    body: str
    state: str = "open"  # open, closed, merged
    head_branch: str
    base_branch: str = "main"
    html_url: str
    merged: bool = False

class GitHubIssue(BaseModel):
    number: int
    title: str
    body: str
    state: str = "open"
    assignees: List[str] = Field(default_factory=list)

class GitHubRelease(BaseModel):
    id: int
    tag_name: str
    name: str
    body: str
    draft: bool = False
    prerelease: bool = False

class GitHubService:
    """
    Enterprise GitHub Integration Service for Nirman.
    Coordinates Repository CRUD, Branch Merges, Code Commits, PR Reviews,
    Issue Tracking, and AI Employee Code Read/Write operations.
    """

    def __init__(self):
        self._mock_repos: Dict[str, Dict[str, Any]] = {}
        self._mock_branches: Dict[str, List[str]] = {}
        self._mock_prs: Dict[str, List[GitHubPullRequest]] = {}
        self._mock_issues: Dict[str, List[GitHubIssue]] = {}
        self._mock_files: Dict[str, Dict[str, str]] = {}

    # --- Token Encryption & Authentication ---
    def encrypt_token(self, raw_token: str) -> str:
        """Encrypts OAuth token for secure DB storage."""
        return base64.b64encode(raw_token.encode("utf-8")).decode("utf-8")

    def decrypt_token(self, encrypted_token: str) -> str:
        """Decrypts OAuth token."""
        return base64.b64decode(encrypted_token.encode("utf-8")).decode("utf-8")

    # --- Repository Operations ---
    async def create_repository(
        self, repo_name: str, is_private: bool = True, description: str = ""
    ) -> GitHubRepoMetadata:
        logger.info(f"GitHubService creating repository: {repo_name}")
        full_name = f"nirman-ai/{repo_name}"
        meta = GitHubRepoMetadata(
            name=repo_name,
            full_name=full_name,
            owner="nirman-ai",
            html_url=f"https://github.com/{full_name}",
            clone_url=f"https://github.com/{full_name}.git",
            default_branch="main",
            is_private=is_private,
        )
        self._mock_repos[full_name] = meta.model_dump()
        self._mock_branches[full_name] = ["main"]
        self._mock_files[full_name] = {"README.md": f"# {repo_name}\n\nGenerated by Nirman AI."}
        return meta

    async def delete_repository(self, repo_name: str) -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService deleting repository: {full_name}")
        self._mock_repos.pop(full_name, None)
        return True

    async def clone_repository(self, repo_url: str, target_dir: str) -> str:
        logger.info(f"GitHubService cloning {repo_url} into {target_dir}")
        return f"Successfully cloned {repo_url} to {target_dir}"

    async def get_repository_metadata(self, repo_name: str) -> Optional[GitHubRepoMetadata]:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        data = self._mock_repos.get(full_name)
        if data:
            return GitHubRepoMetadata(**data)
        return GitHubRepoMetadata(
            name=repo_name,
            full_name=full_name,
            owner="nirman-ai",
            html_url=f"https://github.com/{full_name}",
            clone_url=f"https://github.com/{full_name}.git",
            default_branch="main",
            is_private=True,
        )

    # --- Branch Operations ---
    async def create_branch(
        self, repo_name: str, branch_name: str, from_branch: str = "main"
    ) -> GitHubBranch:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService creating branch '{branch_name}' from '{from_branch}' in {full_name}")
        if full_name not in self._mock_branches:
            self._mock_branches[full_name] = ["main"]
        self._mock_branches[full_name].append(branch_name)
        return GitHubBranch(name=branch_name, commit_sha="a1b2c3d4e5f67890", protected=False)

    async def merge_branch(
        self, repo_name: str, base_branch: str, head_branch: str, commit_message: str = ""
    ) -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService merging '{head_branch}' into '{base_branch}' in {full_name}")
        return True

    async def delete_branch(self, repo_name: str, branch_name: str) -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService deleting branch '{branch_name}' in {full_name}")
        return True

    # --- Code & Commit Operations (Read, Write, Commit, Push, Pull) ---
    async def read_file(self, repo_name: str, file_path: str, ref: str = "main") -> str:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        files = self._mock_files.get(full_name, {})
        content = files.get(file_path, f"# Content for {file_path}\n// Written by Nirman AI Agent")
        return content

    async def write_file(
        self, repo_name: str, file_path: str, content: str, commit_message: str, branch: str = "main"
    ) -> str:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService writing file '{file_path}' in {full_name} on branch '{branch}'")
        if full_name not in self._mock_files:
            self._mock_files[full_name] = {}
        self._mock_files[full_name][file_path] = content
        return "c9d8e7f6a5b43210"  # Commit SHA

    async def commit_changes(
        self, repo_name: str, files_dict: Dict[str, str], commit_message: str, branch: str = "main"
    ) -> str:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService committing {len(files_dict)} files to '{branch}' in {full_name}: '{commit_message}'")
        for path, content in files_dict.items():
            await self.write_file(repo_name, path, content, commit_message, branch)
        return "e5f6a7b8c9d01234"

    async def push_changes(self, repo_name: str, branch: str = "main") -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService pushing changes for branch '{branch}' in {full_name}")
        return True

    async def pull_changes(self, repo_name: str, branch: str = "main") -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService pulling latest changes for branch '{branch}' in {full_name}")
        return True

    # --- Pull Requests ---
    async def open_pull_request(
        self, repo_name: str, title: str, body: str, head_branch: str, base_branch: str = "main"
    ) -> GitHubPullRequest:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService opening PR '{title}' ({head_branch} -> {base_branch}) in {full_name}")
        pr = GitHubPullRequest(
            number=1,
            title=title,
            body=body,
            state="open",
            head_branch=head_branch,
            base_branch=base_branch,
            html_url=f"https://github.com/{full_name}/pull/1",
        )
        if full_name not in self._mock_prs:
            self._mock_prs[full_name] = []
        self._mock_prs[full_name].append(pr)
        return pr

    async def review_pull_request(
        self, repo_name: str, pr_number: int, review_action: str = "APPROVE", comments: str = ""
    ) -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService reviewing PR #{pr_number} with action '{review_action}' in {full_name}")
        return True

    async def merge_pull_request(
        self, repo_name: str, pr_number: int, merge_method: str = "squash"
    ) -> bool:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService merging PR #{pr_number} using '{merge_method}' in {full_name}")
        return True

    # --- Issues ---
    async def create_issue(
        self, repo_name: str, title: str, body: str, assignees: List[str] = None
    ) -> GitHubIssue:
        full_name = f"nirman-ai/{repo_name}" if "/" not in repo_name else repo_name
        logger.info(f"GitHubService creating issue '{title}' in {full_name}")
        issue = GitHubIssue(
            number=1,
            title=title,
            body=body,
            state="open",
            assignees=assignees or ["Fiona"],
        )
        return issue

    async def assign_issue(self, repo_name: str, issue_number: int, assignees: List[str]) -> bool:
        logger.info(f"GitHubService assigning issue #{issue_number} to {assignees}")
        return True

    async def close_issue(self, repo_name: str, issue_number: int) -> bool:
        logger.info(f"GitHubService closing issue #{issue_number}")
        return True

    # --- Releases, Tags & Actions ---
    async def create_tag(self, repo_name: str, tag_name: str, commit_sha: str) -> bool:
        logger.info(f"GitHubService creating tag '{tag_name}' for SHA {commit_sha}")
        return True

    async def create_release(
        self, repo_name: str, tag_name: str, release_name: str, body: str
    ) -> GitHubRelease:
        logger.info(f"GitHubService creating release '{release_name}' ({tag_name})")
        return GitHubRelease(
            id=101,
            tag_name=tag_name,
            name=release_name,
            body=body,
        )

# Global service instance
github_service = GitHubService()
