import { Sidebar } from "@/components/layout/Sidebar";
import { Navbar } from "@/components/layout/Navbar";
import { FolderGit2, Plus, Search, Filter, ArrowRight, Layers, Clock, Activity } from "lucide-react";
import Link from "next/link";

const PROJECTS_LIST = [
  {
    id: "proj-1",
    name: "Nirman SaaS Core Platform",
    slug: "nirman-saas-core",
    description: "Enterprise-grade AI software company platform operating across 20 SDLC phases.",
    phase: "Phase 6: PRD & SRS Specifications",
    health: 98,
    status: "IN_PROGRESS",
    updated: "10 mins ago",
    stack: ["Next.js", "FastAPI", "PostgreSQL", "Docker"]
  },
  {
    id: "proj-2",
    name: "Apex Algorithmic Trading Bot",
    slug: "apex-trading-bot",
    description: "High-frequency trade execution platform with real-time WebSocket telemetry.",
    phase: "Phase 18: Docker & Deployment",
    health: 100,
    status: "COMPLETED",
    updated: "2 hours ago",
    stack: ["Python", "Redis", "Grafana", "WebSockets"]
  },
  {
    id: "proj-3",
    name: "MedPulse Telehealth Analytics",
    slug: "medpulse-telehealth",
    description: "HIPAA compliant patient telemetry analytics SaaS with RAG clinical assistance.",
    phase: "Phase 12: AI Infrastructure",
    health: 95,
    status: "IN_PROGRESS",
    updated: "Yesterday",
    stack: ["React", "Tailwind", "LangChain", "FastAPI"]
  }
];

export default function ProjectsPage() {
  return (
    <div className="flex h-screen bg-[#07090E] text-gray-100 overflow-hidden font-sans">
      <Sidebar />

      <div className="flex-1 flex flex-col min-w-0 overflow-y-auto">
        <Navbar />

        <main className="p-6 max-w-7xl mx-auto w-full space-y-6">
          <div className="flex items-center justify-between border-b border-white/10 pb-5">
            <div>
              <h1 className="text-2xl font-bold text-white tracking-tight">Software Projects Workspace</h1>
              <p className="text-xs text-gray-400 mt-1">Manage and track autonomous software applications generated by Nirman.</p>
            </div>

            <button className="bg-indigo-600 hover:bg-indigo-500 text-white font-medium text-xs px-4 py-2 rounded-lg shadow-glow transition flex items-center gap-2">
              <Plus className="w-3.5 h-3.5" />
              <span>Create Project</span>
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            {PROJECTS_LIST.map((proj) => (
              <div key={proj.id} className="glass-panel p-6 rounded-2xl border border-white/10 glass-panel-hover flex flex-col justify-between space-y-4">
                <div className="space-y-2">
                  <div className="flex items-center justify-between">
                    <span className="px-2.5 py-0.5 rounded text-[10px] font-mono bg-indigo-500/20 text-indigo-300 border border-indigo-500/30 font-semibold">
                      {proj.status}
                    </span>
                    <span className="text-[11px] font-mono text-emerald-400">Health: {proj.health}%</span>
                  </div>

                  <h2 className="text-base font-bold text-white tracking-tight">{proj.name}</h2>
                  <p className="text-xs text-gray-400 leading-relaxed">{proj.description}</p>
                </div>

                <div className="space-y-3 pt-2 border-t border-white/10 text-xs">
                  <div className="flex items-center justify-between text-[11px] font-mono">
                    <span className="text-gray-400">SDLC Status</span>
                    <span className="text-emerald-400 font-semibold">{proj.phase}</span>
                  </div>

                  <div className="flex flex-wrap gap-1.5">
                    {proj.stack.map((tech, idx) => (
                      <span key={idx} className="px-2 py-0.5 rounded text-[10px] font-mono bg-white/5 text-gray-300 border border-white/10">
                        {tech}
                      </span>
                    ))}
                  </div>

                  <Link
                    href={`/projects/${proj.id}`}
                    className="w-full mt-2 bg-[#151824] hover:bg-white/10 text-gray-200 font-medium text-xs py-2 rounded-lg transition flex items-center justify-center gap-2 border border-white/5"
                  >
                    <span>Open Project Hub</span>
                    <ArrowRight className="w-3.5 h-3.5 text-indigo-400" />
                  </Link>
                </div>
              </div>
            ))}
          </div>
        </main>
      </div>
    </div>
  );
}
