"use client";

import React, { useState } from "react";
import { motion } from "framer-motion";
import {
  FileCode2,
  Download,
  Eye,
  Share2,
  History,
  FileText,
  Database,
  Code2,
  ShieldCheck,
  Terminal,
  MoreVertical
} from "lucide-react";

export interface ArtifactData {
  id: string;
  name: string;
  project: string;
  author: string;
  authorAvatar: string;
  type: string;
  version: string;
  size: string;
  updatedAt: string;
  tags: string[];
  content: string;
}

interface ArtifactCardProps {
  artifact: ArtifactData;
  onPreview: (art: ArtifactData) => void;
  onVersionHistory: (art: ArtifactData) => void;
  onShare: (art: ArtifactData) => void;
}

export const ArtifactCard: React.FC<ArtifactCardProps> = ({
  artifact,
  onPreview,
  onVersionHistory,
  onShare,
}) => {
  const getIcon = (type: string) => {
    if (type.includes("SQL")) return Database;
    if (type.includes("Python") || type.includes("React") || type.includes("Code")) return Code2;
    if (type.includes("Docker")) return Terminal;
    if (type.includes("QA") || type.includes("Security")) return ShieldCheck;
    return FileText;
  };

  const Icon = getIcon(artifact.type);

  return (
    <motion.div
      initial={{ opacity: 0, y: 15 }}
      animate={{ opacity: 1, y: 0 }}
      className="glass-card p-5 rounded-2xl border border-white/[0.06] hover:border-indigo-500/40 transition-all flex flex-col justify-between text-left group"
    >
      <div>
        {/* Top Icon & Version Row */}
        <div className="flex items-start justify-between gap-3 mb-3">
          <div className="flex items-center gap-3">
            <div className="w-10 h-10 rounded-xl bg-indigo-500/10 border border-indigo-500/20 flex items-center justify-center text-indigo-400 shrink-0">
              <Icon className="w-5 h-5" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white group-hover:text-indigo-300 transition-colors truncate max-w-[160px]">
                {artifact.name}
              </h3>
              <span className="text-[10px] font-mono text-slate-500">{artifact.project}</span>
            </div>
          </div>

          <span className="text-[9px] font-mono font-bold px-2 py-0.5 rounded bg-indigo-500/20 text-indigo-300 border border-indigo-500/30">
            {artifact.version}
          </span>
        </div>

        {/* Author info & tags */}
        <div className="p-2.5 rounded-xl bg-black/40 border border-white/[0.04] mb-3 space-y-1">
          <div className="flex items-center justify-between text-[10px] font-mono text-slate-400">
            <span>Generated By</span>
            <span className="text-slate-200 font-bold flex items-center gap-1">
              <span>{artifact.authorAvatar}</span> {artifact.author}
            </span>
          </div>
          <div className="flex flex-wrap gap-1 pt-1">
            {artifact.tags.map((tg) => (
              <span key={tg} className="text-[9px] font-mono px-1.5 py-0.5 rounded bg-white/[0.04] text-slate-400">
                #{tg}
              </span>
            ))}
          </div>
        </div>
      </div>

      {/* Card Footer Actions */}
      <div className="pt-3 border-t border-white/[0.04] flex items-center justify-between text-[10px] font-mono text-slate-500">
        <span>{artifact.size} • {artifact.updatedAt}</span>

        <div className="flex items-center gap-1">
          <button
            onClick={() => onPreview(artifact)}
            className="p-1.5 text-slate-400 hover:text-white hover:bg-white/[0.06] rounded-lg transition-colors"
            title="Preview Artifact"
          >
            <Eye className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => onVersionHistory(artifact)}
            className="p-1.5 text-slate-400 hover:text-white hover:bg-white/[0.06] rounded-lg transition-colors"
            title="Version History"
          >
            <History className="w-3.5 h-3.5" />
          </button>
          <button
            onClick={() => onShare(artifact)}
            className="p-1.5 text-slate-400 hover:text-white hover:bg-white/[0.06] rounded-lg transition-colors"
            title="Share Link"
          >
            <Share2 className="w-3.5 h-3.5" />
          </button>
        </div>
      </div>
    </motion.div>
  );
};
