"use client";

import React from "react";
import {
  FileCode2,
  Upload,
  Sparkles,
  Download,
  LayoutGrid,
  List,
  Folder,
  Calendar,
  Layers
} from "lucide-react";

export type ViewMode = "grid" | "list" | "folder" | "timeline";

interface HeaderProps {
  viewMode: ViewMode;
  onViewModeChange: (mode: ViewMode) => void;
  onOpenGenerateModal?: () => void;
}

export const Header: React.FC<HeaderProps> = ({
  viewMode,
  onViewModeChange,
  onOpenGenerateModal,
}) => {
  const views: { id: ViewMode; label: string; icon: React.FC<{ className?: string }> }[] = [
    { id: "grid", label: "Grid", icon: LayoutGrid },
    { id: "list", label: "List", icon: List },
    { id: "folder", label: "Folder Tree", icon: Folder },
    { id: "timeline", label: "Timeline", icon: Calendar },
  ];

  return (
    <div className="flex flex-col md:flex-row md:items-center justify-between gap-6 mb-8 text-left">
      <div>
        <div className="flex items-center gap-2 mb-1">
          <FileCode2 className="w-5 h-5 text-indigo-400" />
          <h1 className="text-2xl md:text-3xl font-extrabold tracking-tight text-white">
            Artifacts &amp; Knowledge Center
          </h1>
        </div>
        <p className="text-xs md:text-sm text-slate-400">
          Central repository for all architecture blueprints, source code, API specs, and documentation generated by Nirman AI.
        </p>
      </div>

      <div className="flex flex-wrap items-center gap-3">
        {/* View Mode Toggle */}
        <div className="flex p-1 rounded-xl bg-black/40 border border-white/[0.08]">
          {views.map((v) => {
            const Icon = v.icon;
            const active = viewMode === v.id;
            return (
              <button
                key={v.id}
                onClick={() => onViewModeChange(v.id)}
                className={`flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-semibold transition-all ${
                  active
                    ? "bg-indigo-600 text-white shadow-md shadow-indigo-600/30"
                    : "text-slate-400 hover:text-slate-200 hover:bg-white/[0.04]"
                }`}
              >
                <Icon className="w-3.5 h-3.5" />
                <span className="hidden sm:inline">{v.label}</span>
              </button>
            );
          })}
        </div>

        {/* Upload Button */}
        <button className="flex items-center gap-1.5 px-3.5 py-2 rounded-xl border border-white/10 hover:border-white/20 bg-white/5 text-slate-200 text-xs font-semibold transition-all">
          <Upload className="w-3.5 h-3.5 text-slate-400" />
          <span className="hidden sm:inline">Upload</span>
        </button>

        {/* Generate Artifact CTA */}
        <button
          onClick={onOpenGenerateModal}
          className="flex items-center gap-1.5 px-4 py-2 rounded-xl bg-gradient-to-r from-indigo-600 to-purple-600 hover:opacity-90 text-white text-xs font-semibold shadow-lg shadow-indigo-600/30 transition-all"
        >
          <Sparkles className="w-4 h-4 text-cyan-400" />
          <span>Generate Artifact</span>
        </button>
      </div>
    </div>
  );
};
