"use client";

import React from "react";
import { FileCode2, Download, FileText, Database, Code2, ShieldCheck, Terminal } from "lucide-react";

export const RecentArtifacts: React.FC = () => {
  const artifacts = [
    { name: "Architecture.md", type: "Markdown Doc", author: "Charlie (Architect)", time: "10m ago", icon: FileText, size: "14.2 KB", color: "text-purple-400" },
    { name: "Database.sql", type: "SQL Schema", author: "George (Database)", time: "15m ago", icon: Database, size: "28.6 KB", color: "text-amber-400" },
    { name: "OpenAPI.yaml", type: "API Spec", author: "Fiona (Backend)", time: "25m ago", icon: Code2, size: "42.1 KB", color: "text-indigo-400" },
    { name: "TestReport.pdf", type: "QA Audit", author: "Ian (QA Specialist)", time: "32m ago", icon: ShieldCheck, size: "110 KB", color: "text-emerald-400" },
    { name: "Dockerfile", type: "Container Config", author: "Kate (DevOps)", time: "45m ago", icon: Terminal, size: "4.8 KB", color: "text-cyan-400" },
    { name: "README.md", type: "Documentation", author: "Leo (Docs Engineer)", time: "1h ago", icon: FileText, size: "8.4 KB", color: "text-slate-400" },
  ];

  return (
    <div className="glass-panel p-6 border border-white/[0.08] text-left">
      <div className="flex items-center justify-between pb-4 border-b border-white/[0.06] mb-6">
        <div className="flex items-center gap-2">
          <FileCode2 className="w-4 h-4 text-indigo-400" />
          <h3 className="text-sm font-bold text-white uppercase tracking-wider">Recently Generated Artifacts</h3>
        </div>
        <a href="/artifacts" className="text-xs font-semibold text-indigo-400 hover:text-indigo-300 transition-colors">
          View All Artifacts
        </a>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
        {artifacts.map((art) => {
          const Icon = art.icon;
          return (
            <div
              key={art.name}
              className="glass-card p-4 rounded-xl border border-white/[0.06] hover:border-indigo-500/30 transition-all flex flex-col justify-between"
            >
              <div>
                <div className="flex items-center justify-between mb-3">
                  <div className="flex items-center gap-2">
                    <Icon className={`w-4 h-4 ${art.color}`} />
                    <span className="text-xs font-bold text-white truncate">{art.name}</span>
                  </div>
                  <span className="text-[9px] font-mono text-slate-400 bg-white/[0.04] px-2 py-0.5 rounded border border-white/[0.06]">
                    {art.type}
                  </span>
                </div>

                <p className="text-[11px] text-slate-400 mb-4">
                  Generated by <strong className="text-slate-200">{art.author}</strong>
                </p>
              </div>

              <div className="flex items-center justify-between pt-2 border-t border-white/[0.04] text-[10px] font-mono text-slate-500">
                <span>{art.time} • {art.size}</span>
                <button
                  className="p-1 text-slate-400 hover:text-white hover:bg-white/[0.06] rounded transition-colors"
                  title="Download Artifact"
                >
                  <Download className="w-3.5 h-3.5" />
                </button>
              </div>
            </div>
          );
        })}
      </div>
    </div>
  );
};
