"use client";

import React from "react";
import { FileCode2, Download, FileText, Database, Code2, ShieldCheck, Terminal } from "lucide-react";
import { useQuery } from "@tanstack/react-query";
import { apiClient } from "@/lib/api-client";

export const RecentArtifacts: React.FC = () => {
  const { data: artifacts = [] } = useQuery({
    queryKey: ["recent-artifacts"],
    queryFn: async () => {
      try {
        const res = await apiClient.get("/pipeline/list");
        if (Array.isArray(res.data) && res.data.length > 0) {
          const mapped: any[] = [];
          res.data.forEach((pipe: any) => {
            (pipe.stages || []).forEach((stg: any) => {
              if (stg.artifact_produced) {
                mapped.push({
                  name: stg.artifact_produced,
                  type: stg.name || "Artifact",
                  author: stg.assigned_agent || "AI Agent",
                  time: stg.completed_at ? new Date(stg.completed_at * 1000).toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : "Recently",
                  icon: stg.name === "Database" ? Database : stg.name === "Deployment" ? Terminal : FileText,
                  size: "18.4 KB",
                  color: "text-cyan-400",
                });
              }
            });
          });
          return mapped.reverse().slice(0, 6);
        }
      } catch (err) {
        // Fallback
      }
      return [];
    },
    refetchInterval: 3000,
  });

  return (
    <div className="glass-panel p-6 border border-white/[0.08] text-left">
      <div className="flex items-center justify-between pb-4 border-b border-white/[0.06] mb-6">
        <div className="flex items-center gap-2">
          <FileCode2 className="w-4 h-4 text-indigo-400" />
          <h3 className="text-sm font-bold text-white uppercase tracking-wider">Recently Generated Artifacts</h3>
        </div>
        <a href="/artifacts" className="text-xs font-semibold text-indigo-400 hover:text-indigo-300 transition-colors">
          View All Artifacts
        </a>
      </div>

      {artifacts.length === 0 ? (
        <div className="py-8 text-center text-xs text-slate-500 font-mono">
          No artifacts produced yet. Launch an autonomous AI project to generate PRDs, system architectures, code, and test suites.
        </div>
      ) : (
        <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
          {artifacts.map((art: any) => {
            const Icon = art.icon || FileText;
            return (
              <div
                key={art.name}
                className="glass-card p-4 rounded-xl border border-white/[0.06] hover:border-indigo-500/30 transition-all flex flex-col justify-between"
              >
                <div>
                  <div className="flex items-center justify-between mb-3">
                    <div className="flex items-center gap-2">
                      <Icon className={`w-4 h-4 ${art.color}`} />
                      <span className="text-xs font-bold text-white truncate">{art.name}</span>
                    </div>
                    <span className="text-[9px] font-mono text-slate-400 bg-white/[0.04] px-2 py-0.5 rounded border border-white/[0.06]">
                      {art.type}
                    </span>
                  </div>

                  <p className="text-[11px] text-slate-400 mb-4">
                    Generated by <strong className="text-slate-200">{art.author}</strong>
                  </p>
                </div>

                <div className="flex items-center justify-between pt-2 border-t border-white/[0.04] text-[10px] font-mono text-slate-500">
                  <span>{art.time} • {art.size}</span>
                  <button
                    className="p-1 text-slate-400 hover:text-white hover:bg-white/[0.06] rounded transition-colors"
                    title="Download Artifact"
                  >
                    <Download className="w-3.5 h-3.5" />
                  </button>
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
};
